fixtures:
  repositories:
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    apt:
      repo: "git://github.com/puppetlabs/puppetlabs-apt.git"
      ref: 2.2.1
  symlinks:
    gitlab_ci_multi_runner: "#{source_dir}"
